#borrre la las keys por seguridad, ya que amazon aws es pago y podrian generarme problemas
cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: 
      secret-key: 
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
      
