cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAWSLKWBK7AO6RKC3P
      secret-key: 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
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
      
